# Generated by Django 5.1.2 on 2024-10-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_investment",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("buy_avg", models.PositiveIntegerField()),
                ("sell_avg", models.PositiveIntegerField()),
                ("post_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ("time_stamp",)},
        ),
        migrations.AlterField(
            model_name="stock",
            name="close_price",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="high_price",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="low_price",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="open_price",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="time_stamp",
            field=models.DateField(),
        ),
    ]
